FROM golang:1.22-alpine

# Install git dan dependencies yang dibutuhkan
RUN apk update && apk add --no-cache git make

# Set working directory
WORKDIR /app

# Copy go.mod dan go.sum
COPY go.mod go.sum ./
RUN go mod download

# Install Air untuk live reloading & Golang Migrate
RUN go install github.com/air-verse/air@latest
RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Copy seluruh source code
COPY . .

# Expose port aplikasi
EXPOSE 8080

# Jalankan Air
CMD ["air", "-c", ".air.toml"]