CREATE TABLE IF NOT EXISTS srs_progress (
    id VARCHAR(36) PRIMARY KEY,
    word_id VARCHAR(36) UNIQUE NOT NULL,
    box_level INT DEFAULT 1,
    next_review_at TIMESTAMP NOT NULL,
    ease_factor FLOAT DEFAULT 2.5,
    repetitions INT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;