basePath: /
definitions:
  domain.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  domain.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  dto.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.CategoryRes:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  dto.CategoryResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  dto.CreateCategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  dto.CreateWordRequest:
    properties:
      category_ids:
        description: Array ID kategori (Opsional)
        items:
          type: string
        type: array
      examples:
        description: Array contoh kalimat (Opsional)
        items:
          $ref: '#/definitions/dto.ExampleRequest'
        type: array
      part_of_speech:
        type: string
      russian_word:
        type: string
      translation:
        type: string
    required:
    - part_of_speech
    - russian_word
    - translation
    type: object
  dto.ExampleRequest:
    properties:
      russian_sentence:
        type: string
      translated_sentence:
        type: string
    required:
    - russian_sentence
    - translated_sentence
    type: object
  dto.GenerateFlashcardRequest:
    properties:
      category_id:
        description: Parameter opsional (tergantung FilterType)
        type: string
      end_date:
        type: string
      filter_type:
        description: 'Opsi: "category", "part_of_speech", "favorite", "date_range",
          "manual", "all"'
        type: string
      part_of_speech:
        type: string
      sort_by:
        description: 'Opsi: "name_asc", "name_desc", "created_asc", "created_desc",
          "updated_desc"'
        type: string
      start_date:
        description: 'Format: YYYY-MM-DD'
        type: string
      word_ids:
        description: Jika pilih manual satu per satu
        items:
          type: string
        type: array
    required:
    - filter_type
    type: object
  dto.LoginRequest:
    properties:
      identifier:
        description: Ubah Email menjadi Identifier (bisa menampung email atau username)
        type: string
      password:
        type: string
    required:
    - identifier
    - password
    type: object
  dto.QuizDetailResponse:
    properties:
      is_correct:
        type: boolean
      russian_word:
        type: string
      translation:
        type: string
      word_id:
        type: string
    type: object
  dto.QuizSessionResponse:
    properties:
      correct_answers:
        type: integer
      created_at:
        type: string
      details:
        description: omitempty agar null untuk user Free
        items:
          $ref: '#/definitions/dto.QuizDetailResponse'
        type: array
      id:
        type: string
      incorrect_answers:
        type: integer
      score:
        type: number
      total_words:
        type: integer
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      no_wa:
        type: string
      password:
        minLength: 6
        type: string
      region:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
  dto.SubmitQuizDetail:
    properties:
      is_correct:
        type: boolean
      word_id:
        type: string
    required:
    - word_id
    type: object
  dto.SubmitQuizRequest:
    properties:
      correct_answers:
        type: integer
      details:
        items:
          $ref: '#/definitions/dto.SubmitQuizDetail'
        type: array
      incorrect_answers:
        type: integer
      score:
        type: number
      status:
        description: Tambahkan ini
        enum:
        - IN_PROGRESS
        - COMPLETED
        type: string
      total_words:
        type: integer
    required:
    - status
    - total_words
    type: object
  dto.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  dto.WordExampleRes:
    properties:
      id:
        type: string
      russian_sentence:
        type: string
      translated_sentence:
        type: string
    type: object
  dto.WordResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/dto.CategoryRes'
        type: array
      created_at:
        type: string
      examples:
        items:
          $ref: '#/definitions/dto.WordExampleRes'
        type: array
      id:
        type: string
      is_favorite:
        type: boolean
      part_of_speech:
        type: string
      russian_word:
        type: string
      translation:
        type: string
    type: object
host: pamagi.mydm.cloud
info:
  contact: {}
  description: Ini adalah dokumentasi API untuk backend Pamagi.
  title: Pamagi API
  version: "1.0"
paths:
  /categories:
    get:
      description: Menampilkan semua daftar kategori milik user yang sedang login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.CategoryResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Ambil Daftar Kategori
      tags:
      - Categories
    post:
      consumes:
      - application/json
      description: 'Menyimpan kategori baru milik user (misal: "Kata Kerja A1")'
      parameters:
      - description: Data Kategori
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CategoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Tambah Kategori Baru
      tags:
      - Categories
  /flashcards/generate:
    post:
      consumes:
      - application/json
      description: Mengambil daftar kata berdasarkan filter (maksimal 20 untuk Free,
        diacak jika lebih)
      parameters:
      - description: Filter Flashcard
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GenerateFlashcardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.WordResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Dapatkan Soal Flashcard
      tags:
      - Flashcard
  /flashcards/history:
    get:
      description: Menampilkan riwayat kuis user (Detail jawaban hanya muncul jika
        Premium)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.QuizSessionResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Ambil Histori Kuis
      tags:
      - Flashcard
  /flashcards/history/{id}:
    delete:
      description: Menghapus satu riwayat kuis berdasarkan ID sesi
      parameters:
      - description: ID Session
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Hapus Histori Kuis
      tags:
      - Flashcard
  /flashcards/submit:
    post:
      consumes:
      - application/json
      description: Menyimpan skor akhir dan detail jawaban user setelah kuis selesai
      parameters:
      - description: Data Skor Kuis
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SubmitQuizRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Kirim Hasil Kuis
      tags:
      - Flashcard
  /login:
    post:
      consumes:
      - application/json
      description: Autentikasi user dan mendapatkan JWT token
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Login user
      tags:
      - Auth
  /logout:
    post:
      description: Menghapus sesi token pengguna dari sistem (Redis)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Logout user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Mendaftarkan akun menggunakan email dan password
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Register user baru
      tags:
      - Auth
  /words:
    get:
      description: Menampilkan daftar kosakata dengan fitur filter
      parameters:
      - description: Filter by Category ID
        in: query
        name: category_id
        type: string
      - description: Filter by Part of Speech (e.g., NOUN)
        in: query
        name: part_of_speech
        type: string
      - description: Filter by Favorite status
        in: query
        name: is_favorite
        type: boolean
      - description: Sorting (newest, oldest)
        in: query
        name: sort_by
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.WordResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Ambil Daftar Kosakata
      tags:
      - Words
    post:
      consumes:
      - application/json
      description: Menyimpan kosakata beserta contoh kalimat opsional
      parameters:
      - description: Data Kosakata
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateWordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Tambah Kosakata Baru
      tags:
      - Words
  /words/{id}/favorite:
    put:
      description: Menandai atau menghapus tanda favorit pada suatu kata
      parameters:
      - description: ID Kosakata
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
      security:
      - ApiKeyAuth: []
      summary: Ubah Status Favorit
      tags:
      - Words
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
